title: Binnu
author: Blogger
email: binnu@binnu.com
description: > # this means to ignore newlines until "baseurl:"
  This is something

# social links
twitter_username: ffreedomkr # DO NOT include the @ character, or else the build will fail!
github_username:  binnu-dev # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
